import Statements
import Kalai

#print axioms Kalai.Cut.eq_of_word_and_divider
#print axioms Kalai.exists_least_supporting_prefix
#print axioms Kalai.firstIndex_eq_length
#print axioms Kalai.recover_rotate
#print axioms Kalai.rotate_word_perm
#print axioms Kalai.rotate_avoids_second
#print axioms Kalai.gluingMap_injective
#print axioms Kalai.enumeratedGluingMap_injective
#print axioms Kalai.FiniteHypergraph.hasEdge_perm
#print axioms Kalai.Embedding.nonRoot_image_mem
#print axioms Kalai.anchoredSupport_root_edge
#print axioms Kalai.anchoredSupport_perm
#print axioms Kalai.anchoredSupport_restrict
#print axioms Kalai.anchoredSupport_joined_first
#print axioms Kalai.glue_embeddings
#print axioms Kalai.anchoredSupport_glue
#print axioms Kalai.anchored_gluing_compatible
#print axioms Kalai.EdgeFirstFrame.remaining_avoids_root
#print axioms Kalai.anchoredGluingMap_injective
#print axioms Kalai.MarkedCut.eq_of_word_index
#print axioms Kalai.MarkedCut.marker_not_earlier
#print axioms Kalai.first_exception_word_injective
#print axioms Kalai.MarkedCut.ofFront_toFront
#print axioms Kalai.MarkedCut.toFront_ofFront
#print axioms Kalai.MarkedCut.front_word_perm
#print axioms Kalai.supportsAt_iff_anchoredSupport
#print axioms Kalai.extend_leaf_embedding
#print axioms Kalai.supportsAt_leaf_of_earlier
#print axioms Kalai.leafTransferMap_injective
#print axioms Kalai.uniqueItems_nodup
#print axioms Kalai.mem_uniqueItems
#print axioms Kalai.ListingFor.card_le_of_injection
#print axioms Kalai.ListingFor.card_le_add_of_injection
#print axioms Kalai.ListingFor.card_eq
#print axioms Kalai.ListingFor.restrict_card_split
#print axioms Kalai.ListingFor.restrict_card_complement
#print axioms Kalai.ListingFor.product_card
#print axioms Kalai.cutCandidates_complete
#print axioms Kalai.markedCandidates_complete
#print axioms Kalai.gluing_count
#print axioms Kalai.anchored_gluing_count
#print axioms Kalai.leaf_transfer_count
#print axioms Kalai.shadowOrderingCount_of_shadow
#print axioms Kalai.shadowOrderingCount_of_not_shadow
#print axioms Kalai.cutEncode_decode
#print axioms Kalai.cutDecode_encode
#print axioms Kalai.cutUniverse_card
#print axioms Kalai.ListingFor.card_eq_of_bijection
#print axioms Kalai.factorial_positive
#print axioms Kalai.insertAtCut_injective
#print axioms Kalai.insertAtCut_surjective
#print axioms Kalai.orderingUniverse_card_factorial
#print axioms Kalai.cutUniverse_card_factorial
#print axioms Kalai.shadowOrderingCount_factorial
#print axioms Kalai.anchored_gluing_count_factorial
#print axioms Kalai.leaf_transfer_count_factorial
#print axioms Kalai.markedAsCut_injective
#print axioms Kalai.markedAsCut_surjective
#print axioms Kalai.terminalCut_count
#print axioms Kalai.markedUniverse_card
#print axioms Kalai.markedUniverse_card_factorial
#print axioms Kalai.anchoredToRootSlice_injective
#print axioms Kalai.anchoredToRootSlice_surjective
#print axioms Kalai.rootSliceCount_eq_cutCount
#print axioms Kalai.fixedMarkerListing_card_factorial
#print axioms Kalai.ListingFor.fiber_card
#print axioms Kalai.orderedEdgeListing_card
#print axioms Kalai.edgeStateCount_normalization
#print axioms Kalai.global_gluing_count
#print axioms Kalai.globalSupportCount_root_perm
#print axioms Kalai.global_marked_leaf_count
#print axioms Kalai.globalMarkedCount_eq_globalSupportCount
#print axioms Kalai.global_leaf_count
#print axioms Kalai.orderedFaceListing_card
#print axioms Kalai.shadowPermutationCount_normalization
#print axioms Kalai.faceInShadow_iff_subset_edge
#print axioms Kalai.singleRoot_global_count
#print axioms Kalai.rootedConstruction_master
#print axioms Kalai.rootedConstruction_shadow_bound
#print axioms Kalai.RootedConstruction.insert_leaf
#print axioms Kalai.SingleRoot.edge_count
#print axioms Kalai.LeafExtension.edge_count
#print axioms Kalai.TightGrowth.rooted
#print axioms Kalai.TightGrowth.edge_count
#print axioms Kalai.orderedEdges_tightGrowth
#print axioms Kalai.IsTightTree.growth
#print axioms Kalai.kalai_shadow_bound
#print axioms Kalai.subsetsOfSize_length
#print axioms Kalai.shadowCount_le_binomial
#print axioms Kalai.kalai_bound
#print axioms Kalai.kalai_contains_tree
#print axioms Kalai.tightEdgeOrder_of_index
#print axioms Kalai.IsTightTree.vertex_count
#print axioms Kalai.Embedding.vertex_count_le
#print axioms Kalai.kalai_master

#print axioms KalaiResults.shadow_bound
#print axioms KalaiResults.binomial_bound
#print axioms KalaiResults.contains_tree
